RESOLUTION: 480
EPOCHS: 1000
BATCH_SIZE: 12
VAL_BATCH_SIZE: 12
LR: 0.005
INPUT_NORM: 'z'
STEP_SIZE: 20
GAMMA: 0.9
WEIGHT_DECAY: 0.00001
PRETRAIN: ''
SAVE_EVERY_EPOCH: False
WORKERS: 8

TRAINER: 'POLYCO'
MODEL: 'POLYCO'
BACKBONE: 'VanillaDeepFPN'
DATASET_NAME: <Add Dataset Name here>
PREPROCESSING: 'AR'
RASTERIZE: True
PRETRAINED: False
BBOX: True
NUM_LEVELS: 4
NUM_POINTS: [8, 16, 32, 64]
SIZES: [240, 120, 60, 30]
FPN: True
FPN_DIM: 256
BBOX_LOSS: 'l1'
BBOX_LOSS_WEIGHT: 2
BBOX_LOSS_WEIGHT_L1: 2
GRAPH_DIM: 128
RASTER_SIZE: [60, 120, 240, 480]
UPSAMPLE_RASTER: False
MASK_SIZE: 480
LOSS: 'dice_ce'
LOSS_WEIGHT: [0.125, 0.25, 0.5, 1.0]

